# Users
# Add users (create & add an email with verification token (plain text) to queue)
POST http://sandbox4/api/users/create
Accept: application/json
Content-Type: application/json

{
    "name": "test11s2sd2as tasdfasf",
    "email": "asdfasssd@asd22.com",
    "country_id": 2
}

###
# Verify user
POST http://sandbox4/api/token/create
Accept: application/json
Content-Type: application/json

{
    "email": "feest.einar@example.net",
    "password": "password",
    "device_name": "android"
}

###
# List users (filter by name OR/AND email OR/AND verified OR/AND country)
GET http://sandbox4/api/users?filter[country]=130&filter[email]=fleffler@example.net
Content-Type: application/json

###
###
# Edit users
POST http://sandbox4/api/users/edit?id=12
Accept: application/json
Content-Type: application/json

{
    "name": "test333",
    "email": "asdf333@asd.com",
    "country_id": "1"
}


###
# Delete users
DELETE http://sandbox4/api/users/delete?id=1
Accept: application/json
Content-Type: application/json


###
###
###
# Projects
# Add projects
POST http://sandbox4/api/projects/create
Accept: application/json
Content-Type: application/json
Authorization: Bearer 1|xcz0whQNjjZMKLezaY6ZtI6KUcyNvEqvwNvK4yDE

{
    "name": "Project 1"
}

###
# Link project to user
POST http://sandbox4/api/projects/linkUser
Accept: application/json
Content-Type: application/json

{
    "projectId": 7,
    "users": [
        9,
        10,
        4
    ]
}


###
# List projects incl. labels (filter by user.email OR/AND user.continent OR/AND labels)
GET http://sandbox4/api/projects?filter[user][continent_id]=&filter[user][email]=&filter[labels]=
Accept: application/json
Content-Type: application/json
Authorization: Bearer 1|xcz0whQNjjZMKLezaY6ZtI6KUcyNvEqvwNvK4yDE


###
# Delete projects
DELETE http://sandbox4/api/projects/delete
Accept: application/json
Content-Type: application/json
Authorization: Bearer 1|xcz0whQNjjZMKLezaY6ZtI6KUcyNvEqvwNvK4yDE

{
    "projectId": 7
}

###
###
###
# Labels
# Add labels
POST http://sandbox4/api/labels/create
Accept: application/json
Content-Type: application/json
Authorization: Bearer 1|xcz0whQNjjZMKLezaY6ZtI6KUcyNvEqvwNvK4yDE

{
    "name": "Label 1"
}

###
# Link label to projects
POST http://sandbox4/api/labels/projectLink
Accept: application/json
Content-Type: application/json
Authorization: Bearer 1|xcz0whQNjjZMKLezaY6ZtI6KUcyNvEqvwNvK4yDE

{
    "labelId": 11,
    "projects": [
        1,
        2,
        3
    ]
}


###
# List labels (filter by user.email OR/AND projects)
GET http://sandbox4/api/labels?filter[user][email]=&filter[projects]=
Accept: application/json
Content-Type: application/json
Authorization: Bearer 1|xcz0whQNjjZMKLezaY6ZtI6KUcyNvEqvwNvK4yDE

###
# Delete labels
DELETE http://sandbox4/api/labels/delete
Accept: application/json
Content-Type: application/json
Authorization: Bearer 1|xcz0whQNjjZMKLezaY6ZtI6KUcyNvEqvwNvK4yDE

{
    "labelId": 4
}
